version: '3.4'

services:
    
    postgresql_database:
        container_name: pg_container
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=Pas4word!
            - POSTGRES_DB=auth_db
        ports:
            - "5432:5432"
        restart: always
        volumes:
            -  database-data:/var/lib/postgresql/data/
            
    pgadmin:
        container_name: pgadming4_container
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
        restart: always
        volumes:
            - pgadmin:/root/.pgadmin
    
volumes:
    database-data:
    pgadmin:
            
